name: get-swift-version
description: >
  Sets various outputs for the active Swift version.
  Optionally provides a `requires` input for enforcing the active version semantically.
inputs:
  requires:
    description: >
      Fails if the active Swift does not satisfy this semantically
      versioned constraint.
outputs:
  version:
    description: The semantic version of the active Swift version.
  major-version:
    description: Eg. Outputs `5` for Swift 5.4.1
  minor-version:
    description: Eg. Outputs `4` for Swift 5.4.1
  patch-version:
    description: Eg. Outputs `1` for Swift 5.4.1
  marketing-version:
    description: Eg. Outputs `5.4` for Swift 5.4.1

runs:
  using: node16
  main: index.js
