on:
  push:
    branches: master
    paths: index.js
  pull_request:
    paths:
      - '*.js'
      - .github/workflows/ci.yml
concurrency:
  group: ${{ github.head_ref || 'push' }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
