on:
  pull_request:
    paths:
      - '*.js'
      - .github/workflows/ci.yml
concurrency:
  group: ${{ github.head_ref || 'push' }}
  cancel-in-progress: true
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: swift
    - run: echo Swift ${{ steps.swift.outputs.version }}
